#!/bin/bash
PROJECT_NAME=$1
mkdir $PROJECT_NAME
cd $PROJECT_NAME
mkdir src
touch src/$PROJECT_NAME.py
mkdir tests
touch tests/__init__.py

echo "import unittest


class Test$PROJECT_NAME(unittest.TestCase):

    def test_failure(self):
        self.assertFalse(True)
" > tests/test_$PROJECT_NAME.py

echo "import sniffer.api
import subprocess

@sniffer.api.runnable
def execute_nose(*args):
    if subprocess.run('python3 -m unittest -f', shell=True).returncode == 0:
        return True
" > scent.py

echo "sniffer
macFSevents
" > requirements.txt

python3 -m venv .venv
source .venv/bin/activate
python3 -m pip install --upgrade pip
python3 -m pip install --requirement requirements.txt
code $test_file || code-insiders $test_file
sniffer